# Site settings
title: Rhys Gregory
email: rhys.m.gregory@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RhysyGregory

# Build settings
markdown: kramdown

highlighter: rouge

kramdown:
  auto_ids: false

permalink: pretty

# Navigation
navigation:
- text: 'Portfolio'
  url: '/c3f63ee769c8f251565e45cf724f6e4efaee0387/portfolio/'
- text: 'About'
  url: '/about/'

defaults:
-
  scope:
    path: ""      # empty string for all files
    type: posts   # limit to posts
  values:
    is_post: true # automatically set is_post=true for all posts

exclude: [
imgs-src,
node_modules,
Gruntfile.js,
package.json,
README.md,
]

keep_files: ['_site/css', '_site/js']