# Site settings
title: Rhys Gregory Portfolio
email: rhys.m.gregory@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RhysyGregory

# Build settings
markdown: kramdown

highlighter: rouge

permalink: pretty

# Navigation
navigation:
- text: 'Portfolio'
  url: '/'
- text: 'About'
  url: '/about/'

exclude: [
css,
js/main.js,
imgs-src,
node_modules,
Gruntfile.js,
package.json,
README.md,
fonts/selection.json
]

keep_files: ['_site/css', '_site/js']